#! /usr/bin/python3

#Flek's Netflix Show reccomender for the Blind. 
'''
    Based off of the category you wish to brwose (or all),
    It will randomly pick a show / movie for you that 
    are available from Netflix with Audio Description tracks.
    Available generes are:

    Action | Comedy | Documentary | Drama | Horror | Kids & Family | Sci-Fi & Fantasy | Thriller | Other
'''
import random
import pyttsx3

def main():
    title = (random.choice(allTitles))
    print(title)
    engine = pyttsx3.init()
    engine.setProperty('rate', 120)  #120 words per minute
    engine.setProperty('volume',0.9) 
    engine.say(title)
    engine.runAndWait()

    engine.say("Based off of the category you wish to browse (or all), It will randomly pick a show / movie for you that is available from Netflix with Audio Description tracks.() Available generes are")
    engine.runAndWait()

    
    #From here We want to get voice navigation features (or very simple imput features)
    
allTitles = [
"Clash of the Titans [Movie Action rated PG-13]",
"#realityhigh [Netflix Film Comedy rated TV-14]",
"13 Reasons Why [Netflix Series Drama rated TV-MA]",
"13TH [Netflix Film Documentary rated TV-MA]",
"1922 [Netflix Film Thriller rated TV-MA]",
"2 Fast 2 Furious [Movie Action rated PG-13]",
"21 Thunder [Netflix Series Drama rated TV-MA]",
"22 July [Netflix Film Drama rated R]",
"3Below: Tales of Arcadia [Netflix Animated Series Kids & Family rated TV-Y7-FV]",
"42 [Movie Drama rated PG-13]",
"47 Metres Down [Movie Thriller rated PG-13]",
"6 Balloons [Netflix Film Drama rated TV-MA]",
"6 Years [Movie Drama Not Rated]",
"7 Days Out [Netflix Series Documentary rated TV-PG]",
"72 Dangerous Animals: Asia [Netflix Science & Nature Series Documentary rated TV-14]",
"72 Dangerous Animals: Latin America [Netflix Science & Nature Series Documentary rated TV-14]",
"A Christmas Prince [Netflix Film Drama rated TV-PG]",
"A Christmas Prince: The Royal Wedding [Netflix Film Drama rated TV-PG]",
"A Futile and Stupid Gesture [Netflix Film Comedy rated TV-MA]",
"A Series of Unfortunate Events [Netflix Series Kids & Family rated TV-PG]",
"A StoryBots Christmas [Netflix Animated Film Kids & Family rated TV-Y]",
"A Tale of Two Kitchens [Netflix Film Documentary rated TV-G]",
"A Wrinkle in Time [Disney Movie Kids & Family rated PG]",
"A.I. Artificial Intelligence [Movie Sci-Fi & Fantasy rated PG-13]",
"About a Boy [Movie Comedy rated PG-13]",
"About Time [Movie Comedy rated R]",
"Abstract: The Art of Design [Netflix Series Documentary rated TV-14]",
"Afflicted [Netflix Series Documentary rated TV-MA]",
"Africa [British Science & Nature TV Series Documentary rated TV-PG]",
"After Life [Netflix Series Comedy rated TV-MA]",
"Alex Strangelove [Netflix Film Comedy rated TV-MA]",
"Alexa & Katie [Netflix Series Kids & Family rated TV-Y7]",
"Alias Grace [Netflix Series Drama rated TV-MA]",
"Ali's Wedding [Netflix Film Comedy rated TV-MA]",
"All About the Washingtons [Netflix Series Comedy rated TV-PG]",
"All Hail King Julien [Netflix Animated Series Kids & Family rated TV-Y7-FV]",
"All Hail King Julien: Exiled [Netflix Animated Series Kids & Family rated TV-Y7-FV]",
"All In My Family [Netflix Film Documentary rated TV-14]",
"Altered Carbon [Netflix Series Sci-Fi & Fantasy rated TV-MA]",
"Always Be My Maybe [Netflix Film Comedy rated PG-13]",
"Amanda Knox [Netflix Film Documentary rated TV-MA]",
"Amateur [Netflix Film Drama rated TV-MA]",
"Amazing Interiors [Netflix Series Reality TV rated TV-PG]",
"American Vandal [Netflix Series Comedy rated TV-MA]",
"An American Tail [Animated Movie Kids & Family rated G]",
"An American Tail: Fievel Goes West [Animated Movie Kids & Family rated G]",
"Angela's Christmas [Netflix Film Kids & Family rated TV-G]",
"Angels & Demons [Movie Thriller rated PG-13]",
"ANIMA [Netflix Film Drama rated TV-PG]",
"Anne with an E [Netflix Series Drama rated TV-PG]",
"Anon [Netflix Film Sci-Fi & Fantasy rated TV-MA]",
"Another Life [Netflix Series Sci-Fi & Fantasy rated TV-14] ",
"Ant-Man and the Wasp [Movie Action rated PG-13]",
"Apostle [Netflix Film Horror rated TV-MA]",
"ARQ [Netflix Film Thriller rated TV-MA]",
"Arrested Development [TV Series, now Netflix Comedy rated TV-14]",
"As Above, So Below [Movie Horror rated R]",
"Ash vs. Evil Dead [TV Series Horror rated TV-MA]",
"Ask the Doctor [Netflix Science & Nature Series Documentary rated TV-PG]",
"Ask the StoryBots [Netflix Animated Series Kids & Family rated TV-Y]",
"Atypical [Netflix Series Comedy rated TV-MA]",
"Audrie & Daisy [Netflix Film Documentary rated TV-MA]",
"Avengers: Infinity War [Movie Action rated PG-13]",
"Awake: The Million Dollar Game [Netflix Series Reality TV rated TV-PG]",
"Back with the Ex [Netflix Series Reality TV rated TV-MA]",
"Backstage [TV Series Kids & Family rated TV-G]",
"Bad Blood [Netflix Series Drama rated TV-MA]",
"Balto [Animated Movie Kids & Family rated G]",
"Barbie & Her Sisters in a Pony Tale [Animated Movie Kids & Family rated TV-Y]",
"Barbie Dreamhouse Adventures [Animated TV Series Kids & Family rated TV-Y]",
"Barbie in Princess Power [Animated Movie Kids & Family rated TV-Y]",
"Barbra: The Music ... The Mem'ries ... The Magic! [Netflix Music Documentary Music rated TV-14]",
"Barry [Netflix Film Drama rated TV-MA]",
"BASEketball [Movie Comedy rated R]",
"Batman Begins [Movie Sci-Fi & Fantasy rated PG-13]",
"Battlefish [Netflix Series Reality TV rated TV-MA]",
"Bayonet [Netflix Film Drama rated TV-MA]",
"Bean: The Ultimate Disaster Movie [Movie Comedy rated PG-13]",
"Beasts of No Nation [Netflix Film Drama Not Rated]",
"Beat Bugs [Netflix Animated Series Kids & Family rated TV-Y]",
"Beat Bugs: All Together Now [Netflix Animated Film Kids & Family rated TV-Y]",
"Beats [Netflix Film Drama rated TV-MA]",
"Bedtime Stories [Disney Movie Kids & Family rated PG]",
"Bee Movie [Animated Movie Kids & Family rated PG]",
"Been So Long [Netflix Film Music rated TV-MA]",
"Before I Wake [Netflix Film Horror rated PG-13]",
"Benji [Netflix Film Kids & Family rated TV-PG]",
"Best.Worst.Weekend.Ever. [Netflix Series Kids & Family rated PG]",
"Better Call Saul [TV Series Drama rated TV-MA]",
"Between [Netflix Series Sci-Fi & Fantasy rated TV-14]",
"Big Miracle [Movie Drama rated PG]",
"Big Mouth [Netflix Animated Adult Series Comedy rated TV-MA]",
"Bill Nye Saves the World [Netflix Series TV Variety rated TV-14]",
"Billy Elliot [Movie Drama rated R]",
"Bird Box [Netflix Film Sci-Fi & Fantasy rated R] (Audio Described in 11 languages!)",
"Birthmarked [Movie Comedy rated TV-MA]",
"Black Earth Rising [Netflix Series Drama rated TV-MA]",
"Black Hawk Down [Movie Action rated R]",
"Black Lightning [TV Series Action rated TV-14]",
"Black Mirror [Netflix Series Drama rated TV-MA] (NOTE: Current season AD should be available by June 24)",
"Black Mirror: Bandersnatch [Netflix Interactive** Movie Drama rated TV-MA]",
"Black Panther [Movie Action rated PG-13]",
"Black Summer [Netflix Series Horror rated TV-MA]",
"Blackway [Movie Thriller rated PG-13]",
"Bleach [Netflix Film Action rated TV-14]",
"Bloodline [Netflix Series Drama rated TV-MA]",
"Blown Away [Netflix Series Reality TV rated TV-PG]",
"Blue Jay [Movie Drama rated TV-MA]",
"Bobby Kennedy for President [Netflix Series Documentary rated TV-MA]",
"Bob's Broken Sleigh [Animated Movie Kids & Family rated TV-G]",
"Bodyguard [Netflix Series Drama rated TV-MA]",
"BoJack Horseman Christmas Special: Sabrina's Christmas Wish [Netflix Animated Adult Movie Comedy rated TV-MA]",
"BoJack Horseman [Netflix Animated Adult Series Comedy rated TV-MA]",
"Bokeh [Movie Drama rated TV-14]",
"Bolt [Disney Animated Movie Kids & Family rated PG]",
"BONDING [Netflix Series Drama rated TV-MA]",
"Border Security: America's Front Line [TV Series Reality TV rated TV-14]",
"Bottersnikes & Gumbles [Netflix Animated Series Kids & Family rated TV-Y7]",
"Boys in the Trees [Movie Thriller rated TV-MA]",
"Brahman Naman [Netflix Film Comedy rated TV-MA]",
"Brain on Fire [Netflix Film Drama rated PG-13]",
"Brainchild [Netflix Series Kids & Family rated TV-Y7]",
"Brené Brown: The Call to Courage [Netflix Film Documentary rated TV-14]",
"Bridget Jones's Baby [Movie Romance rated R]",
"Bright [Netflix Film Action rated TV-MA]",
"Bring It On: In It to Win It [Movie Comedy rated PG-13]",
"Bruno and Boots: Go Jump in the Pool [Movie Kids & Family rated TV-PG]",
"Bruno and Boots: The Wizzle War [Movie Kids & Family rated TV-PG]",
"Bruno and Boots: This Can't Be Happening at Macdonald Hall [Movie Kids & Family rated TV-PG]",
"Buddy Thunderstruck [Netflix Interactive** Animated Series Kids & Family rated TV-PG]",
"Buddy Thunderstruck: The Maybe Pile [Netflix Film Kids & Family rated TV-PG]",
"Burlesque: Heart of the Glitter Tribe [Movie Documentary rated TV-MA]",
"Burn After Reading [Movie Comedy rated R]",
"Burning Sands [Netflix Film Drama rated TV-MA]",
"Calibre [Netflix Film Thriller rated TV-MA]",
"Call the Midwife [British TV Series Drama rated TV-14]",
"Cam [Netflix Film Thriller rated TV-MA]",
"Candy Jar [Netflix Film Drama rated TV-14]",
"Captive [Netflix Series Documentary rated TV-MA]",
"Car Masters: Rust to Riches [Netflix Series Reality TV rated TV-PG]",
"Care Bears & Cousins [Netflix Animated Series Kids & Family rated TV-Y]",
"Cargo [Netflix Film Horror rated TV-MA]",
"Carmen Sandiego [Netflix Animated Series Kids & Family rated TV-Y7-FV]",
"Carrie Pilby [Movie Comedy rated TV-14]",
"Case [Netflix Series Drama rated TV-MA]",
"Casper [Movie Kids & Family rated PG]",
"Casting JonBenet [Netflix Film Documentary rated TV-14]",
"Castlevania [Netflix Animated Series Anime rated TV-MA]",
"Catching Feelings [Netflix Film Comedy rated TV-MA]",
"Chambers [Netflix Series Horror rated TV-MA]",
"Champions [TV Series Comedy rated TV-14]",
"Chappaquiddick [Movie Drama rated PG-13]",
"Chappie [Movie Sci-Fi & Fantasy rated R]",
"Charlie's Colorforms City [Netflix Animated Series Drama rated TV-Y]",
"Chasing Cameron [Netflix Series Reality TV rated TV-14]",
"Chasing Coral [Netflix Science & Nature Film Documentary rated TV-PG]",
"Chef's Table [Netflix Series Documentary rated TV-14]",
"Chef's Table: France [Netflix Series Documentary rated TV-14] (Both English and French description)",
"Chelsea Does [Netflix Series Documentary rated TV-MA]",
"Chewing Gum [Netflix Series Comedy rated TV-MA]",
"Chicken Little [Disney Animated Movie Kids & Family rated G]",
"Chilling Adventures of Sabrina [Netflix Series Horror rated TV-14]",
"Chip and Potato [Netflix Animated Series Kids & Family rated TV-Y]",
"Christmas Inheritance [Netflix Film Drama rated TV-PG]",
"Christopher Robin [Disney Movie Kids & Family rated PG]",
"Churchill's Secret Agents: The New Recruits [Netflix Series Reality TV rated TV-MA]",
"Cirque du Freak: The Vampire's Assistant [Movie Action rated PG-13]",
"City of Joy [Netflix Film Documentary rated TV-MA]",
"Clash of the Titans [Movie Action rated PG-13] ",
"Clinical [Netflix Series Horror rated TV-MA]",
"Close [Netflix Film Action rated TV-MA]",
"Cloud Atlas [Movie Drama rated R]",
"Cloudy with a Chance of Meatballs [Movie Kids & Family rated PG]",
"Cloudy with a Chance of Meatballs [TV Series Kids & Family rated TV-Y7]",
"Coco [Disney Animated Movie Kids & Family rated PG]",
"Coin Heist [Netflix Film Kids & Family rated TV-14]",
"Collateral [Netflix Series Drama rated TV-MA]",
"Come Sunday [Netflix Film Drama rated TV-14]",
"Comedians in Cars Getting Coffee [Netflix Series Comedy rated TV-14]",
"Conor McGregor: Notorious [Documentary Sports rated R]",
"Conversations with a Killer: The Ted Bundy Tapes [Netflix Series Documentary rated TV-MA]",
"Cooked [Netflix Series Documentary rated TV-PG]",
"Cooking on High [Netflix Series Reality TV rated TV-MA]",
"Cop Car [Movie Thriller rated R]",
"Coraline [Animated Movie Kids & Family rated PG]",
"Counterfeiting in Suburbia [Movie Thriller rated TV-14]",
"Counterpunch [Netflix Film Documentary rated TV-MA]",
"Crashing [Netflix Series Comedy rated TV-MA]",
"Crazyhead [Netflix Series Comedy rated TV-MA]",
"Creep 2 [Movie Horror rated TV-MA]",
"Creep [Movie Horror rated R]",
"Creeped Out [Netflix Series Kids & Family rated TV-Y7]",
"Cricket Fever: Mumbai Indians [Netflix Documentary Series Sports rated TV-MA]",
"Criminal Minds [TV Series Drama rated TV-14] (Reportedly description only available thru season 12)",
"Crouching Tiger, Hidden Dragon: Sword of Destiny [Netflix Film Action rated TV-14]",
"Cuba and the Cameraman [Netflix Film Documentary rated TV-14]",
"Cuckoo [Netflix Series Comedy rated TV-14]",
"Cupcake & Dino - General Services [Netflix Animated Series Kids & Family rated TV-Y7]",
"Daddy Day Care [Movie Kids & Family rated PG]",
"Damnation [TV Series Drama rated TV-14]",
"Dancing Queen [Netflix Series Reality TV rated TV-14]",
"Danger Mouse [Netflix Animated Series Kids & Family rated TV-Y7]",
"Dark Tourist [Netflix Series Documentary rated TV-MA]",
"Dark [Netflix Series Thriller rated TV-MA]",
"Dating Around [Netflix Series Reality TV rated TV-MA]",
"Daughters of Destiny [Netflix Series Documentary rated TV-PG]",
"David Brent: Life on the Road [Netflix Series Comedy rated TV-MA]",
"Dawn of the Croods [Netflix Animated Series Kids & Family rated TV-Y7]",
"Day of the Dead: Bloodline [Movie Horror rated R]",
"Dead to Me [Netflix Series Drama rated TV-MA]",
"Dear White People [Netflix Series Comedy rated TV-MA]",
"Death at a Funeral [Movie Comedy rated R]",
"Death by Magic [Netflix Series Reality TV rated TV-14]",
"Death Note [Netflix Film Horror rated TV-MA] (The MOVIE, not the Japanese SERIES!)",
"Death Race: Beyond Anarchy [Movie Action rated R]",
"Degrassi: Next Class [Netflix Series Drama rated TV-PG]",
"Deidra & Laney Rob a Train [Netflix Film Comedy rated TV-14]",
"Derek [Netflix Series Drama rated TV-14]",
"Derren Brown: Miracle [Netflix TV Series Reality TV rated TV-MA]",
"Derren Brown: Sacrifice [Netflix TV Series Reality TV rated TV-MA]",
"Derry Girls [Netflix Series Comedy rated TV-MA]",
"Designated Survivor [TV Series Drama rated TV-14]",
"Despicable Me 3 [Movie Kids & Family rated PG]",
"Dinotrux Supercharged [Netflix Animated Series Kids & Family rated TV-Y7-FV]",
"Dinotrux [Netflix Animated Series Kids & Family rated TV-Y7-FV]",
"Dirty Money [Netflix Series Documentary rated TV-14]",
"Disenchantment [Netflix Animated Series Comedy rated TV-14]",
"Disjointed [Netflix Series Comedy rated TV-MA]",
"Dogs [Netflix Series Documentary rated TV-PG]",
"Don't Think Twice [Movie Comedy rated R]",
"Dope [Netflix Series Documentary rated TV-MA] (Season 2 is missing description",
"Dr. Seuss' The Cat in the Hat [Movie Kids & Family rated PG]",
"Dragons: Race to the Edge [Netflix Animated Series Kids & Family rated TV-Y7-FV]",
"DreamWorks Home: For the Holidays [Netflix Animated Film Kids & Family rated TV-Y7]",
"Drug Lords [Netflix Series Documentary rated TV-MA]",
"Duck Butter [Movie Drama rated TV-MA]",
"Duck Duck Goose [Netflix Animated Film Kids & Family rated PG]",
"Dude [Netflix Film Drama rated TV-MA]",
"Dumplin' [Netflix Film Drama rated PG-13]",
"Dynasty [TV Series Drama rated TV-14] (This is a reboot of the 1980s TV series)",
"Easy [Netflix Series Comedy rated TV-MA]",
"Edgar Rice Burroughs' Tarzan and Jane [Netflix Animated Series Kids & Family rated TV-Y7-FV] (NOTE: This is NOT the Disney version of a similar name)",
"El Camino Christmas [Netflix Film Comedy rated TV-MA]",
"Elite [Netflix Series Drama rated TV-MA]",
"Empire Games [Netflix Series Documentary rated TV-14]",
"End Game [Netflix Film Documentary rated TV-PG]",
"E-Team [Netflix Film Documentary Not Rated]",
"Ever After High [Netflix Animated Series Kids & Family rated TV-Y7]",
"Everything Sucks! [Netflix Series Comedy rated TV-14]",
"Evil Genius: the True Story of America's Most Diabolical Bank Heist [Netflix Series Documentary rated TV-MA]",
"Evolution [Movie Sci-Fi & Fantasy rated PG-13]",
"Exhibit A [Netflix Science & Nature Series Documentary rated TV-MA]",
"Expedition China [Disneynature Science & Nature Film Documentary rated G]",
"Explained [Netflix Series Documentary rated TV-14]",
"Extinction [Netflix Film Sci-Fi & Fantasy rated TV-MA]",
"Extreme Engagement [Netflix Series Reality TV rated TV-MA]",
"Extremely Wicked, Shockingly Evil and Vile [Netflix Film Drama rated R]",
"Extremis [Netflix Film Documentary rated TV-PG] (Please check suitability for children!)",
"F is for Family [Netflix Animated Series Comedy rated TV-MA]",
"Family Reunion [Netflix Series Kids & Family rated TV-PG]",
"Fangbone [Animated TV Series Kids & Family rated TV-Y7]",
"Fastest Car [Netflix Series Reality TV rated TV-MA] (AD is a synthesized voice)",
"Father of the Year [Netflix Film Comedy rated TV-14]",
"Fearless [Netflix Series Documentary rated TV-14]",
"Feminists: What Were They Thinking? [Netflix Film Documentary rated TV-MA]",
"FIGHTWORLD [Netflix Series Documentary rated TV-MA]",
"Fire Chasers [Netflix Series Documentary rated TV-MA]",
"First and Last [Netflix Series Documentary rated TV-MA]",
"First Match [Netflix Film Drama rated TV-MA]",
"First They Killed My Father [Netflix Film Drama rated TV-MA]",
"Five Came Back [Netflix Series Documentary rated TV-MA]",
"Flaked [Netflix Series Comedy rated TV-MA]",
"Flinch [Netflix Series Reality TV rated PG]",
"Flint Town [Netflix Series Documentary rated TV-MA]",
"Flock of Four [Movie Drama rated TV-MA]",
"Follow This [Netflix Film Documentary rated TV-MA]",
"Formula 1: Drive to Survive [Netflix Documentary Series Sports rated TV-MA]",
"Free Rein [Netflix Series Kids & Family rated TV-G]",
"Free Rein: The Twelve Neighs of Christmas [Netflix Film Kids & Family rated TV-Y7]",
"Free Rein: Valentine's Day [Netflix Film Kids & Family rated TV-Y7]",
"Friends from College [Netflix Series Comedy rated TV-MA]",
"Frontier [Netflix Series Drama rated TV-MA]",
"Frozen Planet [British Science & Nature TV Series Documentary rated TV-PG]",
"Full Out [Movie Kids & Family rated TV-PG]",
"Fuller House [Netflix Series Comedy rated TV-G]",
"FullMetal Alchemist [Netflix Film Action rated TV-14] (NOTE: There are 3 videos similarly named",
"FYRE: The Greatest Party That Never Happened [Netflix Film Documentary rated TV-MA]",
"Game Over, Man! [Netflix Film Comedy rated TV-MA]",
"Generation Iron 3 [Documentary Sports rated TV-MA]",
"George of the Jungle 2 [Disney Movie Kids & Family rated PG]",
"Gerald's Game [Netflix Film Horror rated TV-MA]",
"Get Me Roger Stone [Netflix Film Documentary rated TV-MA]",
"Get Smart [Movie Comedy rated PG-13]",
"G-Force [Disney Movie Comedy rated PG]",
"Ghost Patrol [Animated Movie Kids & Family rated TV-Y7-FV]",
"Gilmore Girls: A Year in the Life [Netflix Series Comedy rated TV-14]",
"Girlboss [Netflix Series Comedy rated TV-MA]",
"Girlfriend's Day [Netflix Film Comedy rated TV-MA]",
"Girls Incarcerated [Netflix Series Reality TV rated TV-MA]",
"Glee [TV Series Drama rated TV-PG]",
"Glitch [Netflix Series Drama rated TV-MA] (The SERIES, not the movie!)",
"Glitter Force Doki Doki [Netflix Animated Series Kids & Family rated TV-Y7]",
"Glitter Force [Netflix Animated Series Kids & Family rated TV-Y7]",
"GLOW [Netflix Series Comedy rated TV-MA]",
"Gnome Alone [Netflix Animated Film Kids & Family rated PG]",
"Godless [Netflix Series Western rated TV-MA]",
"Good Girls [TV Series Comedy rated TV-14]",
"Good Sam [Netflix Film Kids & Family rated TV-PG]",
"Goon: Last of the Enforcers [Movie Comedy rated R]",
"Goosebumps 2: Haunted Halloween [Movie Kids & Family rated PG]",
"Gotham [TV Series Drama rated TV-14]",
"Grace and Frankie [Netflix Series Comedy rated TV-MA]",
"Gran Torino [Movie Drama rated R]",
"Grass Is Greener [Netflix Film Documentary rated TV-MA]",
"Great News [TV Series Comedy rated TV-14]",
"Greenhouse Academy [Netflix Series Kids & Family rated TV-PG]",
"Greenleaf [TV Series Drama rated TV-14]",
"Gridlocked [Movie Action rated R]",
"Gypsy [Netflix Series Drama rated TV-MA]",
"H2O: Mermaid Adventures [Netflix Animated Series Kids & Family rated TV-Y7]",
"Halo: The Fall of Reach [Movie Sci-Fi & Fantasy rated TV-14]",
"Handsome Devil [Movie Drama rated TV-MA]",
"Handsome: A Netflix Mystery Movie [Netflix Film Comedy rated TV-MA]",
"Happy Anniversary [Movie Comedy rated TV-MA]",
"Happy Valley [Netflix Series Drama rated TV-MA]",
"Happy! [TV Series Comedy rated TV-MA]",
"Harry and the Hendersons [Movie Comedy rated PG]",
"Harvey Girls Forever! [Netflix Animated Series Kids & Family rated TV-Y7]",
"Haters Back Off [Netflix Series Comedy rated TV-14]",
"Haunted [Netflix Series Reality TV rated TV-MA]",
"Heavy Rescue: 401 [Netflix Series Reality TV rated TV-MA] (Description starts with season 2)",
"Hemlock Grove [Netflix Series Horror rated TV-MA]",
"Her [Movie Drama rated R]",
"Heroin(e) [Netflix Film Documentary rated TV-14]",
"Hi Score Girl [Netflix Animated Series Anime rated TV-PG]",
"High Flying Bird [Netflix Film Drama rated TV-MA]",
"Hilda [Netflix Animated Series Kids & Family rated TV-Y7]",
"Hip-Hop Evolution [Netflix Series Documentary rated TV-MA]",
"Hold the Dark [Netflix Film Thriller rated TV-MA]",
"Holding the Man [Movie Drama Not Rated]",
"Holidays [Movie Horror Not Rated]",
"Home: Adventures with Tip & Oh [Netflix Animated Series Kids & Family rated TV-Y7]",
"HOMECOMING: A film by Beyoncé [Netflix Documentary Music rated TV-MA]",
"Hostiles [Movie Drama rated R]",
"Hot Bot [Movie Comedy Not Rated]",
"Hot Girls Wanted [Netflix Film Documentary Not Rated]",
"Hot Girls Wanted: Turned On [Netflix Series Documentary rated TV-MA]",
"Hotel Beau Séjour [Netflix Series Drama rated TV-14]",
"Hotel Transylvania 3: Summer Vacation [Animated Movie Kids & Family rated PG]",
"House of Cards [Netflix Series Thriller rated TV-MA]",
"How It Ends [Netflix Film Thriller rated TV-MA]",
"How the Grinch Stole Christmas [Movie Kids & Family rated PG]",
"How to Sell Drugs Online (Fast) [Netflix Series Drama rated TV-MA]",
"Huge in France [Netflix Series Comedy rated TV-MA]",
"Hush [Movie Horror rated R]",
"I AM A KILLER [Netflix Series Documentary rated TV-MA]",
"I Am Mother [Netflix Film Sci-Fi & Fantasy rated TV-14]",
"I Am the Pretty Thing That Lives in the House [Netflix Film Thriller rated TV-14]",
"I Don't Feel at Home in This World Anymore [Netflix Film Drama rated TV-MA]",
"Ibiza: Love Drunk [Netflix Film Comedy rated TV-MA]",
"iBOY [Netflix Film Thriller rated TV-MA]",
"Icarus [Netflix Film Documentary rated TV-MA]",
"I'll Sleep When I'm Dead [Netflix Film Documentary rated TV-MA]",
"Illang: The Wolf Brigade [Netflix Film Action rated TV-MA]",
"Imperial Dreams [Netflix Film Drama rated TV-MA]",
"In Bruges [Movie Comedy rated R]",
"In The Dark [TV Series Drama rated TV-14]",
"Indiana Jones and the Last Crusade [Movie Action rated PG-13]",
"Indiana Jones and the Raiders of the Lost Ark [Movie Action rated PG]",
"Indiana Jones and the Temple of Doom [Movie Action rated PG]",
"Indiscretion [Movie Drama rated TV-MA]",
"Insatiable [Netflix Series Comedy rated TV-MA]",
"Inside the Criminal Mind [Netflix Series Documentary rated TV-MA]",
"Inside the Real Narcos [Netflix Series Documentary rated TV-MA]",
"Inside the World's Toughest Prisons [Netflix Series Documentary rated TV-MA] (Description starts with season 2)",
"Instant Hotel [Netflix Series Reality TV rated TV-MA]",
"Internet Famous [Movie Comedy rated TV-14]",
"Into the Inferno [Netflix Film Documentary rated TV-PG]",
"IO [Netflix Film Sci-Fi & Fantasy rated TV-14]",
"Irreplaceable You [Netflix Film Romance rated TV-MA]",
"It Was Fifty Years Ago Today! The Beatles: Sgt. Pepper and Beyond [Movie Documentary rated TV-14]",
"It's Bruno! [Netflix Series Comedy rated TV-MA]",
"Jack Whitehall: Travels with My Father [Netflix Series Comedy rated TV-MA] ",
"Jailbirds [Netflix Series Reality TV rated TV-MA]",
"Jim & Andy: The Great Beyond - Featuring a Very Special, Contractually Obligated Mention of Tony Clifton [Netflix Film Documentary rated TV-MA]",
"Jo Pil-ho: The Dawning Rage [Movie Drama rated TV-MA]",
"Joan Didion: The Center Will Not Hold [Netflix Film Documentary rated TV-14]",
"John Carter [Disney Movie Action rated PG-13]",
"Jonathan Strange & Mr Norrell [British TV Series Drama rated TV-14]",
"Joshua: Teenager vs. Superpower [Netflix Film Documentary rated TV-14]",
"Joy [Netflix Film Drama rated TV-MA]",
"Juanita [Netflix Film Drama rated TV-MA]",
"Julie & Julia [Movie Comedy rated PG-13]",
"Julie's Greenroom [Netflix Series Kids & Family rated TV-Y]",
"Jupiter Ascending [Movie Sci-Fi & Fantasy rated PG-13]",
"Jupiter Ascending [Movie Sci-Fi & Fantasy rated PG-13] ",
"Justin Bieber: Never Say Never [Documentary Music rated G]",
"Justin Timberlake + the Tennessee Kids [Netflix Documentary Music rated TV-PG]",
"Justin Time GO! [Netflix Animated Series Kids & Family rated TV-Y]",
"Kazoops! [Netflix Animated Series Kids & Family rated TV-Y]",
"Keith Richards: Under the Influence [Netflix Film Documentary rated TV-PG]",
"Kevin Hart's Guide to Black History [Netflix Film Comedy rated TV-PG]",
"Kibaoh Klashers [Animated TV Series Kids & Family rated TV-Y7]",
"Kill the Messenger [Movie Drama rated R]",
"Kingdom of Us [Netflix Series Documentary rated TV-MA]",
"Kiss Me First [Netflix Series Drama rated TV-MA]",
"Knock Down The House [Netflix Film Documentary rated PG]",
"Kodachrome [Netflix Film Drama rated TV-MA]",
"Kong: King of the Apes [Netflix Animated Series Kids & Family rated TV-Y7-FV]",
"Kronk's New Groove [Disney Animated Movie Kids & Family rated G]",
"Kulipari: An Army of Frogs [Netflix Animated Series Kids & Family rated TV-Y7-FV]",
"Kulipari: Dream Walker [Netflix Animated Series Kids & Family rated TV-Y7-FV]",
"Lady Dynamite [Netflix Series Comedy rated TV-MA]",
"Lakeview Terrace [Movie Thriller rated PG-13]",
"Larry Charles' Dangerous World of Comedy [Netflix Series Documentary rated TV-MA]",
"Larva Island [Netflix Animated Series Comedy rated TV-Y7]",
"Last Breath [British Movie Documentary rated TV-14]",
"Last Chance U [Netflix Series Documentary rated TV-MA]",
"Layer Cake [Movie Thriller rated R]",
"Learning Songs by Little Baby Bum: Nursery Rhyme Friends [Animated TV Series Kids & Family rated TV-Y]",
"Legend Quest [Netflix Animated Series Kids & Family rated TV-Y7]",
"LEGO Bionicle: The Journey to One [Netflix Animated Series Kids & Family rated TV-Y7-FV]",
"LEGO Elves: Secrets of Elvendale [Netflix Animated Series Kids & Family rated TV-Y7]",
"LEGO Friends: The Power of Friendship [Netflix Animated Series Kids & Family rated TV-Y7]",
"LEGO Jurassic World: The Indominus Escape [Animated Movie Kids & Family rated TV-Y7]",
"Leroy & Stitch [Disney Animated Movie Kids & Family rated G]",
"Lessons from a School Shooting: Notes from Dunblane [Netflix Film Documentary rated TV-14]",
"Life Overtakes Me [Netflix Film Documentary rated TV-PG]",
"Like Father [Netflix Film Comedy rated TV-MA]",
"Lilo & Stitch 2: Stitch Has A Glitch [Disney Animated Movie Kids & Family rated G]",
"Lilo & Stitch [Disney Animated Movie Kids & Family rated PG]",
"Lincoln [Movie Drama rated PG-13]",
"Lionheart [Netflix Film Comedy rated TV-PG]",
"Little Baby Bum: Nursery Rhyme Friends [Netflix Series Kids & Family rated TV-Y]",
"Little Evil [Movie Comedy rated TV-MA]",
"Liv and Maddie [Disney TV Series Kids & Family rated TV-G] (No description available for seasons 1 and 3)",
"Llama Llama [Netflix Animated Series Kids & Family rated TV-Y]",
"Long Shot [Netflix Film Documentary rated TV-14]",
"Longmire [TV Series, now Netflix Western rated TV-14]",
"Losers [Netflix Documentary Series Sports rated TV-MA]",
"Lost & Found Music Studios [Netflix Series Kids & Family rated TV-G]",
"Lost in Space [Netflix Series Sci-Fi & Fantasy rated TV-PG]",
"Love [Netflix Series Comedy rated TV-MA]",
"Love, Death & Robots [Netflix Animated Adult Series Comedy rated TV-MA]",
"Love, Rosie [British Movie Comedy rated R] (Pull date Aug 6)",
"Lovesick [Netflix Series Comedy rated TV-MA]",
"Lucifer [TV Series, now Netflix Drama rated TV-14]",
"Luna Petunia [Netflix Animated Series Kids & Family rated TV-Y]",
"Luna Petunia: Return to Amazia [Netflix Animated Series Kids & Family rated TV-Y]",
"Lunatics [Netflix Series Comedy rated TV-MA]",
"Mac & Devin Go to High School [Movie Comedy rated R]",
"Mad Men [TV Series Drama rated TV-14]",
"Magic for Humans [Netflix Series Reality TV rated TV-14]",
"Magic Mike [Movie Drama rated R]",
"Making a Murderer [Netflix Series Documentary rated TV-14]",
"Mako Mermaids: An H2O Adventure [Netflix Series Kids & Family rated TV-G]",
"Malevolent [Netflix Film Horror rated TV-MA]",
"Malibu Rescue [Netflix Film Kids & Family rated TV-G]",
"Malibu Rescue: The Series [Netflix Series Kids & Family rated G]",
"Manhattan Romance [Movie Comedy rated TV-14]",
"Maniac [Netflix Series Drama rated TV-MA]",
"Manson Family Vacation [Movie Comedy Not Rated]",
"Marcella [Netflix Series Drama rated TV-MA]",
"Marching Orders [Netflix Series Documentary rated TV-14]",
"Marco Polo [Netflix Series Drama rated TV-MA]",
"Marco Polo: One Hundred Eyes [Netflix Film Drama rated TV-MA]",
"Mariah Carey's Merriest Christmas [TV Special Music rated TV-G]",
"Marlon [TV Series Comedy rated TV-PG]",
"Marvel Super Hero Adventures: Frost Fight! [Animated Movie Kids & Family rated PG]",
"Marvel's Daredevil [Netflix Series Action rated TV-MA]",
"Marvel's Iron Fist [Netflix Series Action rated TV-MA]",
"Marvel's Iron Man & Hulk: Heroes United [Animated Movie Action rated PG]",
"Marvel's Jessica Jones [Netflix Series Action rated TV-MA]",
"Marvel's Luke Cage [Netflix Series Action rated TV-MA]",
"Marvel's The Defenders [Netflix Series Action rated TV-MA]",
"Marvel's The Punisher [Netflix Series Action rated TV-MA]",
"Mary Poppins Returns [Disney Movie Kids & Family rated PG]",
"Mascots [Netflix Film Comedy rated TV-MA]",
"Masha and the Bear [Animated TV Series Comedy rated TV-Y]",
"Masha's Spooky Stories [Animated TV Series Kids & Family rated TV-Y]",
"Masha's Tales [Animated TV Series Kids & Family rated TV-Y]",
"Master of None [Netflix Series Comedy rated TV-MA]",
"MeatEater [Netflix Science & Nature Series Documentary rated TV-14] (Description starts with season 7)",
"Medal of Honor [Netflix Series Documentary rated TV-MA]",
"Medici [Netflix Series Drama rated TV-MA]",
"Meet Joe Black [Movie Drama rated PG-13]",
"Meet the Robinsons [Animated Movie Kids & Family rated G]",
"Megamind [Animated Movie Kids & Family rated PG]",
"Mercury 13 [Netflix Film Documentary rated TV-PG]",
"Mercy [Netflix Series Thriller rated TV-MA]",
"Merlí [Netflix Series Drama rated TV-PG]",
"Message from the King [Netflix Film Thriller rated TV-MA]",
"Miami Vice [Movie Action rated R]",
"Mickey's House of Villains [Disney Animated Movie Kids & Family rated TV-Y7]",
"Mickey's Magical Christmas: Snowed in at the House of Mouse [Disney Animated Movie Kids & Family rated TV-G]",
"Mickey's Once Upon a Christmas [Disney Animated Movie Kids & Family rated G]",
"Mickey's Twice Upon a Christmas [Disney Animated Movie Kids & Family rated G]",
"Middle School: The Worst Years of My Life [Movie Kids & Family rated PG]",
"Mighty Little Bheem [Netflix Animated Series Comedy rated TV-Y]",
"Million Pound Menu [Netflix Series Reality TV rated TV-MA]",
"Mindhorn [Netflix Film Comedy rated TV-MA]",
"MINDHUNTER [Netflix Series Thriller rated TV-MA]",
"Minecraft: Story Mode [Animated Movie Kids & Family rated TV-Y7-FV]",
"Miss Me This Christmas [Movie Romance rated TV-14]",
"Money Heist [Netflix Series Thriller rated TV-MA]",
"Monster High: 13 Wishes [Animated Movie Kids & Family rated TV-Y7]",
"Monster High: Frights, Camera, Action! [Animated Movie Kids & Family rated TV-Y7]",
"Monster High: Ghouls Rule [Animated Movie Kids & Family rated TV-Y7]",
"Monster House [Animated Movie Kids & Family rated PG]",
"Most Beautiful Thing [Netflix Series Kids & Family rated TV-MA]",
"Motown Magic [Netflix Animated Series Kids & Family rated TV-Y]",
"Mowgli: Legend of the Jungle [Netflix Film Action rated PG-13]",
"Mr. Iglesias [Netflix Series Comedy rated TV-14]",
"Mudbound [Netflix Film Drama rated R]",
"Mulan [Disney Animated Movie Kids & Family rated G]",
"Mune: Guardian of the Moon [Animated Movie Kids & Family rated PG]",
"Murder Mystery [Netflix Film Comedy rated PG-13]",
"Mute [Netflix Film Sci-Fi & Fantasy rated TV-MA]",
"My Beautiful Broken Brain [Netflix Film Documentary rated TV-14]",
"My Happy Family [Netflix Film Drama rated TV-14]",
"My Little Pony Equestria Girls: Legend of Everfree [Animated Movie Kids & Family rated TV-Y7]",
"My Next Guest Needs No Introduction With David Letterman [Netflix Series TV Variety rated TV-MA]",
"Nailed It! Holiday! [Netflix Series Reality TV rated TV-PG]",
"Nailed It! [Netflix Series Reality TV rated TV-PG]",
"Naked [Netflix Film Comedy rated TV-14]",
"Nappily Ever After [Netflix Film Drama rated TV-MA]",
"Narcos [Netflix Series Drama rated TV-MA]",
"Narcos: Mexico [Netflix Series Drama rated TV-MA]",
"National Treasure [Movie Action rated PG]",
"NCIS [TV Series Drama rated TV-14] (Description starts with season 3)",
"Neo Yokio [Netflix Animated Series Comedy rated TV-MA]",
"Netflix Presents: The Characters [Netflix Series TV Variety rated TV-14]",
"New Girl [TV Series Comedy rated TV-14] (Description starts with season 2)",
"Newness [Movie Drama rated TV-MA]",
"Next Gen [Netflix Animated Film Kids & Family rated TV-PG]",
"Nick and Norah's Infinite Playlist [Movie Comedy rated PG-13]",
"No Good Nick [Netflix Series Kids & Family rated PG]",
"Nobody Speak: Trials of the Free Press [Netflix Film Documentary rated TV-14]",
"Norsemen [TV Series Comedy rated TV-MA]",
"Northern Rescue [Netflix Series Drama rated TV-14]",
"Notes on Blindness [British Documentary Drama rated TV-PG]",
"Obsessed [Movie Thriller rated PG-13]",
"Octonauts [Animated TV Series Kids & Family rated TV-Y]",
"Oh, Ramona! [Movie Comedy rated TV-MA]",
"Okja [Netflix Film Drama rated TV-MA]",
"On My Block [Netflix Series Comedy rated TV-14]",
"One Day at a Time [Netflix Series Comedy rated TV-PG]",
"One Day [Movie Drama rated PG-13] (Note: There are two movies with this title",
"One Last Shot [Movie Comedy rated TV-MA]",
"One of Us [Netflix Film Documentary rated TV-14]",
"Opening Night [Movie Comedy rated TV-14]",
"Oprah Winfrey Presents: When They See Us Now [Netflix Film Documentary rated TV-14]",
"Orange Is the New Black [Netflix Series Comedy rated TV-MA]",
"Other People [Movie Drama rated TV-MA]",
"Our Planet [Netflix Science & Nature Series Documentary rated TV-G]",
"Our Souls at Night [Netflix Film Drama rated TV-14]",
"Out of Many, One [Netflix Film Documentary rated TV-PG]",
"Outlaw King [Netflix Film Action rated R]",
"Outside In [Movie Drama rated TV-MA]",
"Ozark [Netflix Series Thriller rated TV-MA]",
"P. King Duckling [Animated TV Series Kids & Family rated TV-Y]",
"P.S. I Love You [Movie Drama rated PG-13]",
"Pachamama [Netflix Animated Film Kids & Family rated PG]",
"Pacific Heat [Netflix Animated Series Comedy rated TV-14]",
"Pac-Man and the Ghostly Adventures [TV Series Kids & Family rated TV-Y7]",
"Pac's Scary Halloween [Animated Movie Kids & Family rated TV-Y7]",
"Paddleton [Netflix Film Drama rated TV-MA]",
"Paradise PD [Netflix Animated Series Comedy rated TV-MA]",
"Paradox [Netflix Film Drama rated TV-MA]",
"Paranoid [Netflix Series Drama rated TV-14]",
"Parenthood [TV Series Comedy rated TV-14] (Description starts with season 5)",
"Parks and Recreation [TV Series Comedy rated TV-14] (Description starts with season 5)",
"Party Monster: Scratching the Surface [Movie Comedy rated TV-14]",
"Paul Blart: Mall Cop [Movie Comedy rated PG]",
"Peaky Blinders [Netflix Series Drama rated TV-MA]",
"Pee-wee's Big Holiday [Netflix Film Kids & Family rated PG]",
"Penny Dreadful [TV Series Horror rated TV-MA]",
"Peter Rabbit [Movie Kids & Family rated PG]",
"Pine Gap [Netflix Series Drama rated TV-MA]",
"Pineapple Express [Movie Comedy rated R]",
"Pinky Malinky [Netflix Animated Series Kids & Family rated TV-Y7]",
"Planet 51 [Animated Movie Kids & Family rated PG]",
"Planet Earth II [British Science & Nature TV Series Documentary rated TV-G]",
"Planet Earth [British Science & Nature TV Series Documentary rated PG]",
"Pocahontas [Disney Animated Movie Kids & Family rated G]",
"Point Blank [Netflix Film Action rated TV-MA]",
"Polar [Netflix Film Action rated TV-MA]",
"Ponysitters Club [Netflix Series Kids & Family rated TV-Y7]",
"Pooh's Grand Adventure: The Search for Christopher Robin [Disney Animated Movie Kids & Family rated G]",
"Pope Francis: A Man of His Word [Movie Documentary rated PG]",
"Popples [Netflix Animated Series Kids & Family rated TV-Y]",
"Prince of Peoria [Netflix Series Kids & Family rated TV-Y7]",
"Prince of Peoria: A Christmas Moose Miracle [Netflix Series Kids & Family rated TV-Y7]",
"Print the Legend [Netflix Film Documentary rated TV-14]",
"Private Life [Netflix Film Drama rated R]",
"Project Mc2 [Netflix Series Kids & Family rated TV-Y7]",
"Puffin Rock [Netflix Animated Series Drama rated TV-Y]",
"Puss in Book: Trapped in an Epic Tale [Netflix Interactive** Animated Movie Kids & Family rated TV-Y7]",
"Queer Eye [Netflix Series Reality TV rated TV-14]",
"Quincy [Netflix Film Documentary rated TV-MA]",
"Quiz Show [Movie Drama rated PG-13]",
"Race to Witch Mountain [Movie Kids & Family rated PG]",
"Ralph Breaks the Internet: Wreck-It Ralph 2 [Disney Animated Movie Kids & Family rated PG]",
"Ram Dass, Going Home [Netflix Film Documentary rated TV-14]",
"Rapture [Netflix Series Documentary rated TV-MA]",
"Real Rob [TV Series Comedy rated TV-MA]",
"Rebellion [Netflix Series Drama rated TV-MA]",
"Rebirth [Netflix Film Drama rated TV-MA]",
"Reboot: The Guardian Code [Netflix Series Kids & Family rated TV-Y7-FV]",
"Recess: Taking the Fifth Grade [Animated Movie Kids & Family rated G]",
"Recovery Boys [Netflix Film Documentary rated TV-MA]",
"ReMastered: Devil at the Crossroads [Netflix Film Documentary rated TV-14]",
"ReMastered: Massacre at the Stadium [Netflix Film Documentary rated TV-MA]",
"ReMastered: The Lion's Share [Netflix Film Documentary rated TV-14]",
"ReMastered: The Miami Showband Massacre [Netflix Film Documentary rated TV-MA]",
"ReMastered: The Two Killings of Sam Cooke [Netflix Film Documentary rated TV-MA]",
"ReMastered: Tricky Dick & The Man in Black [Netflix Film Documentary rated TV-MA]",
"ReMastered: Who Killed Jam Master Jay? [Netflix Film Documentary rated TV-MA]",
"ReMastered: Who Shot the Sheriff [Netflix Film Documentary rated TV-14]",
"Requiem [Netflix Series Thriller rated TV-MA]",
"Resurface [Netflix Film Documentary rated TV-MA]",
"Retribution [Netflix Series Drama rated TV-MA] (The SERIES, not the movie!)",
"Reversing Roe [Netflix Film Documentary rated TV-14]",
"Revolutionary Road [Movie Drama rated R]",
"Richie Rich [Netflix Series Kids & Family rated TV-G]",
"Rim of the World [Netflix Film Action rated TV-14]",
"River [Netflix Series Drama rated TV-MA]",
"Riverdale [TV Series Drama rated TV-14]",
"Robozuna [Netflix Series Kids & Family rated TV-Y7-FV]",
"Rodney King [Netflix Film Drama rated TV-MA]",
"Rolling Thunder Revue: A Bob Dylan Story by Martin Scorsese [Netflix Documentary Music rated TV-MA]",
"Roman Empire [Netflix Series Comedy rated TV-MA] (Also known as Roman Empire: Reign of Blood)",
"Room [Movie Comedy rated R]",
"Rotten [Netflix Series Documentary rated TV-MA]",
"Roxanne Roxanne [Netflix Film Drama rated TV-MA]",
"Royal Pains [TV Series Drama rated TV-PG] (Description starts with season 4)",
"Russian Doll [Netflix Series Comedy rated TV-MA]",
"RV [Movie Comedy rated PG]",
"Safe [Netflix Series Thriller rated TV-MA]",
"Sahara [Netflix Animated Film Kids & Family rated TV-Y7]",
"SAINT SEIYA: Knights of the Zodiac [Netflix Animated Series Sci-Fi & Fantasy rated TV-14]",
"Salt Fat Acid Heat [Netflix Series Documentary rated TV-PG]",
"Sand Castle [Netflix Film Action rated TV-MA]",
"Sandy Wexler [Netflix Film Comedy rated TV-14]",
"Santa Buddies [Disney Movie Kids & Family rated G]",
"Santa Clarita Diet [Netflix Series Comedy rated TV-MA]",
"Santa Pac's Merry Berry Day [Animated Movie Kids & Family rated TV-Y7]",
"Santa Paws 2: The Santa Pups [Disney Movie Kids & Family rated G]",
"Savage Dog [Movie Action rated TV-MA]",
"Saving Capitalism [Netflix Film Documentary rated TV-PG]",
"Saving Mr. Banks [Disney Movie Drama rated PG-13]",
"Schindler's List [Movie Drama rated R]",
"Scorpion King 5: Book of Souls [Movie Sci-Fi & Fantasy rated PG-13]",
"Scott Pilgrim vs. the World [Movie Comedy rated PG-13]",
"Scream [TV Series Horror rated TV-14]",
"Secret City [Netflix Series Thriller rated TV-MA]",
"Secret Obsession [Netflix Film Thriller rated TV-14]",
"See You Yesterday [Netflix Film Sci-Fi & Fantasy rated TV-MA]",
"Seeing Allred [Netflix Film Documentary rated TV-14]",
"Selling Sunset [Netflix Series Documentary rated TV-MA]",
"Sense8 [Netflix Series Sci-Fi & Fantasy rated TV-MA]",
"Set It Up [Netflix Film Comedy rated TV-14]",
"Seven Pounds [Movie Drama rated PG-13]",
"Seven Seconds [Netflix Series Drama rated TV-MA]",
"Sex Education [Netflix Series Comedy rated TV-MA]",
"Shadow [Netflix Series Action rated TV-MA]",
"She-Ra and the Princesses of Power [Netflix Animated Series Kids & Family rated TV-Y7-FV]",
"Sherlock Holmes [Movie Action rated PG-13]",
"Sherlock [British TV Series Drama rated TV-14]",
"She's Gotta Have It [Netflix Series Drama rated TV-MA] (The SERIES, not the movie)",
"She's Out of My League [Movie Comedy rated R]",
"Shimmer Lake [Netflix Film Drama rated TV-MA]",
"Shirkers [Netflix Film Documentary rated TV-14]",
"Shooter [TV Series Action rated TV-MA]",
"Shopkins: Chef Club [TV Series Kids & Family rated TV-Y]",
"Shopkins: Wild [TV Series Kids & Family rated TV-Y]",
"Shopkins: World Vacation [TV Series Kids & Family rated TV-Y]",
"Shot in the Dark [Netflix Series Reality TV rated TV-MA] (AD is a synthesized voice)",
"Sick Note [Netflix Series Comedy rated TV-MA]",
"Sierra Burgess Is a Loser [Netflix Film Comedy rated PG-13]",
"Sisters [Netflix Series Drama rated TV-MA]",
"Sky Ladder: The Art of Cai Guo-Qiang [Netflix Film Documentary rated TV-MA] (Both English and Mandarin description)",
"Skylanders Academy [Netflix Animated Series Kids & Family rated TV-Y7]",
"Slasher [TV Series Thriller rated TV-MA]",
"Small Crimes [Netflix Film Drama rated TV-MA]",
"SMOSH: The Movie [Movie Comedy rated PG-13]",
"Snow Buddies [Disney Movie Kids & Family rated G]",
"Sofia the First [Disney Animated Series Kids & Family rated TV-Y]",
"Solo: A Star Wars Story [Movie Sci-Fi & Fantasy rated PG-13]",
"Some Assembly Required [Netflix Series Kids & Family rated TV-G]",
"Somebody Feed Phil [Netflix Series Documentary rated TV-PG]",
"Someone Great [Netflix Film Romance rated R]",
"Space Buddies [Disney Movie Kids & Family rated G]",
"Special Correspondents [Netflix Film Comedy rated TV-MA]",
"Special [Netflix Series Comedy rated TV-MA]",
"Spectral [Netflix Film Sci-Fi & Fantasy rated TV-14]",
"Spider-Man: Into the Spider-Verse [Animated Movie Action rated PG]",
"Spirit Riding Free [Netflix Animated Series Kids & Family rated TV-Y7]",
"Spotless [TV Series Drama rated TV-MA]",
"Springsteen on Broadway [Netflix Documentary Music rated TV-MA]",
"Spy Kids: Mission Critical [Netflix Series Kids & Family rated TV-Y7-FV]",
"Star Wars: Episode VIII: The Last Jedi [Movie Action rated PG-13]",
"Stardust [Movie Sci-Fi & Fantasy rated PG-13]",
"Stay Here [Netflix Series Reality TV rated TV-PG]",
"Step Sisters [Netflix Film Comedy rated TV-14]",
"Stitch! The Movie [Disney Animated Movie Kids & Family rated G]",
"StoryBots Super Songs [Animated TV Series Kids & Family rated TV-Y]",
"Stranger Things [Netflix Series Thriller rated TV-14]",
"Straw Dogs [Movie Thriller rated R] (Pull date Aug 31)",
"Street Food [Netflix Series Documentary rated G]",
"Stretch Armstrong & the Flex Fighters [Netflix Animated Series Kids & Family rated TV-Y7-FV]",
"Stretch Armstrong: The Breakout [Netflix Animated Film Kids & Family rated TV-Y7-FV]",
"Strong Island [Netflix Film Documentary rated TV-MA]",
"Struggle: The Life and Lost Art of Szukalski [Netflix Film Documentary rated TV-MA]",
"Sugar Rush [Netflix Series Reality TV rated TV-PG]",
"Sunderland 'Til I Die [Netflix Series Documentary rated TV-MA]",
"Super Drags [Netflix Animated Adult Series Comedy rated TV-MA]",
"Super Monsters and the Wish Star [Netflix Film Kids & Family rated TV-Y]",
"Super Monsters Furever Friends [Netflix Animated Film Kids & Family rated TV-Y]",
"Super Monsters Monster Pets [Netflix Animated Series Kids & Family rated TV-Y]",
"Super Monsters Save Halloween [Netflix Animated Film Kids & Family rated TV-Y]",
"Super Monsters [Netflix Animated Series Kids & Family rated TV-Y]",
"Sweeney Todd: The Demon Barber of Fleet Street [Movie Drama rated R]",
"Take Me [Movie Comedy rated TV-MA]",
"Take the 10 [Netflix Series Comedy rated TV-MA]",
"Take Your Pills [Netflix Film Documentary rated TV-14]",
"Tales by Light [Netflix Science & Nature Series Documentary rated TV-PG]",
"Tales of the City [Netflix Series Drama rated TV-MA]",
"Tallulah [Netflix Film Drama rated TV-MA]",
"Tarzan [Disney Movie Kids & Family rated G]",
"TAU [Netflix Film Sci-Fi & Fantasy rated R]",
"Taylor Swift reputation Stadium Tour [Netflix Music Documentary Music rated TV-PG]",
"Team Foxcatcher [Netflix Film Documentary rated TV-14]",
"That '70s Show [TV Series Comedy rated TV-14] (Description only available for season 7)",
"The 40-Year-Old Virgin [Movie Comedy rated R] (Pull date Aug 16)",
"The Adventures of Puss in Boots [Netflix Animated Series Kids & Family rated TV-Y7-FV]",
"The After Party [Netflix Film Comedy rated TV-MA]",
"The American Meme [Netflix Film Documentary rated TV-MA]",
"The Angel [Netflix Film Drama rated TV-MA]",
"The Babysitter [Netflix Film Horror rated TV-MA]",
"The Ballad of Buster Scruggs [Netflix Film Western rated R]",
"The Big Family Cooking Showdown [Netflix Series Reality TV rated TV-PG] (Description starts with season 2)",
"The Black Godfather [Netflix Documentary Music rated TV-MA]",
"The Bleeding Edge [Netflix Film Documentary rated TV-14]",
"The Blue Planet: A Natural History of the Oceans [British Science & Nature TV Series Documentary rated TV-G]",
"The Boss Baby: Back in Business [Netflix Series Kids & Family rated TV-Y7]",
"The Boy Who Harnessed the Wind [Netflix Film Drama rated TV-14]",
"The Breaker Upperers [Netflix Film Comedy rated TV-MA]",
"The Break-Up [Movie Comedy rated PG-13]",
"The Bye Bye Man [Movie Thriller rated PG-13]",
"The Casketeers [Netflix Series Reality TV rated TV-14]",
"The Chef Show [Netflix Series Documentary rated TV-MA]",
"The Christmas Chronicles [Netflix Film Kids & Family rated TV-PG]",
"The Cloverfield Paradox [Netflix Film Sci-Fi & Fantasy rated TV-MA]",
"The Confession Tapes [Netflix Series Documentary rated TV-MA]",
"The Conjuring [Movie Horror rated R]",
"The Croods [Animated Movie Kids & Family rated PG] ",
"The Crown [Netflix Series Drama rated TV-MA]",
"The Cuba Libre Story [Netflix Series Documentary rated TV-14]",
"The Curious Creations of Christine McConnell [Netflix Series TV Variety rated TV-PG]",
"The Dark Knight [Movie Action rated PG-13]",
"The Death and Life of Marsha P. Johnson [Netflix Film Documentary rated TV-MA]",
"The Deep [Animated TV Series Kids & Family rated TV-Y10]",
"The Dirt [Netflix Film Sci-Fi & Fantasy rated TV-MA]",
"The Disappearance of Madeleine McCann [Netflix Series Sci-Fi & Fantasy rated TV-14]",
"The Discovery [Netflix Film Sci-Fi & Fantasy rated TV-MA]",
"The Do-Over [Netflix Film Comedy rated TV-MA]",
"The Dragon Prince [Netflix Animated Series Kids & Family rated TV-Y7-FV]",
"The Drowning [Movie Thriller rated TV-MA]",
"The Drunk and on Drugs Happy Funtime Hour [TV Series Comedy rated TV-MA]",
"The Edge of Democracy [Netflix Film Documentary rated TV-14]",
"The Edge of Seventeen [Movie Comedy rated R]",
"The Emoji Movie [Movie Kids & Family rated PG] (Pull date Aug 8)",
"The Emperor's New Groove [Disney Movie Kids & Family rated G]",
"The End of the F***ing World [Netflix Series Drama rated TV-MA]",
"The Epic Tales of Captain Underpants [Netflix Animated Series Kids & Family rated TV-Y7]",
"The Fall [Netflix Series Drama rated TV-MA]",
"The Fast and the Furious [Movie Action rated PG-13]",
"The Fast and the Furious: Tokyo Drift [Movie Action rated PG-13]",
"The Final Table [Netflix Reality TV Series Reality TV rated TV-PG]",
"The Frankenstein Chronicles [Netflix Series Thriller rated TV-MA]",
"The Fundamentals of Caring [Netflix Film Drama rated TV-MA]",
"The Furchester Hotel [British TV Series Kids & Family rated TV-Y]",
"The Get Down [Netflix Series Drama rated TV-MA]",
"The Good Cop [Netflix Series Drama rated TV-PG]",
"The Good Place [TV Series Comedy rated TV-14]",
"The Great British Baking Show [Netflix Series Reality TV rated TV-PG] (Description starts with season 5)",
"The Great Hack [Netflix Film Documentary rated TV-MA] ",
"The Guernsey Literary and Potato Peel Pie Society [Netflix Film Drama rated TV-14]",
"The Hangover [Movie Comedy rated R]",
"The Haunting of Hill House [Netflix Series Horror rated TV-MA]",
"The Highwaymen [Netflix Film Drama rated R]",
"The Hitchhiker's Guide to the Galaxy [Movie Comedy rated PG] (Pull date Aug 20)",
"The Holiday Calendar [Netflix Film Romance rated TV-PG]",
"The Hollow [Netflix Animated Series Kids & Family rated TV-Y7-FV]",
"The House Bunny [Movie Comedy rated PG-13]",
"The House Bunny [Movie Comedy rated PG-13] ",
"The Hundred-Foot Journey [Movie Comedy rated PG]",
"The Hurricane Heist [Movie Action rated PG-13]",
"The Incredible Jessica James [Netflix Film Comedy rated TV-MA]",
"The Incredibles 2 [Disney Animated Movie Kids & Family rated PG]",
"The Indian Detective [Netflix Series Comedy rated TV-14]",
"The Innocent Man [Netflix Series Documentary rated TV-MA]",
"The Innocents [Netflix Series Drama rated TV-MA]",
"The Investigator: A British Crime Story [Netflix British TV Series Documentary rated TV-14]",
"The Ivory Game [Netflix Science & Nature Film Documentary rated TV-14]",
"The Jane Austen Book Club [Movie Drama rated PG-13]",
"The Keepers [Netflix Series Documentary rated TV-MA]",
"The Kindergarten Teacher [Netflix Film Drama rated R]",
"The Kissing Booth [Netflix Film Romance rated TV-14]",
"The Kominsky Method [Netflix Series Comedy rated TV-MA]",
"The Land of Steady Habits [Netflix Film Drama rated TV-MA]",
"The Last Czars [Netflix Series Drama rated TV-MA]",
"The Last Kingdom [Netflix Series Action rated TV-MA]",
"The Last Laugh [Netflix Film Comedy rated TV-MA]",
"The Last O.G. [TV Series Comedy rated TV-MA]",
"The Last Summer [Netflix Film Comedy rated TV-14]",
"The Legacy of a Whitetail Deer Hunter [Netflix Film Drama rated TV-14]",
"The Legend of 420 [Movie Documentary rated TV-MA]",
"The Legend of Cocaine Island [Netflix Film Documentary rated TV-MA]",
"The Letdown [Netflix Series Comedy rated TV-MA]",
"The Little Prince [Netflix Animated Series Kids & Family rated PG]",
"The Magic School Bus Rides Again [Netflix Animated Series Kids & Family rated TV-Y]",
"The Magic School Bus [Animated TV Series Kids & Family rated TV-Y]",
"The Mars Generation [Netflix Film Documentary rated TV-PG]",
"The Meyerowitz Stories (New and Selected) [Netflix Film Drama rated TV-MA]",
"The Mist [TV Series Horror rated TV-MA]",
"The Most Hated Woman in America [Netflix Film Drama rated TV-MA]",
"The Mr. Peabody and Sherman Show [Netflix Animated Series Kids & Family rated TV-Y7]",
"The New Legends of Monkey [Netflix Series Kids & Family rated TV-PG]",
"The Nutcracker and the Four Realms [Disney Movie Kids & Family rated PG]",
"The OA [Netflix Series Drama rated TV-MA]",
"The Office (U.S.) [TV Series Comedy rated TV-14] (Only the final season 9 has description)",
"The Open House [Netflix Film Horror rated TV-MA]",
"The Order [Netflix Series Drama rated TV-MA]",
"The Other One: The Long Strange Trip of Bob Weir [Netflix Film Documentary rated TV-14]",
"The Other Side of the Wind [Netflix Film Drama rated R]",
"The Outsider [Netflix Film Drama rated TV-MA]",
"The Package [Netflix Film Comedy rated TV-MA]",
"The Perfect Date [Netflix Film Romance rated TV-14]",
"The Perfection [Netflix Film Thriller rated TV-MA]",
"The Pirate Fairy [Disney Animated Movie Kids & Family rated G]",
"The Pixar Story [Disney Movie Documentary rated G]",
"The Polka King [Netflix Series Comedy rated TV-14]",
"The Power of Grayskull: The Definitive History of He-Man and the Masters of the Universe [Movie Documentary rated TV-PG]",
"The Princess and the Frog [Disney Animated Movie Kids & Family rated G]",
"The Princess Switch [Netflix Film Drama rated TV-PG]",
"The Rachel Divide [Netflix Film Documentary rated TV-MA]",
"The Ranch [Netflix Series Comedy rated TV-MA]",
"The Red Sea Diving Resort [Netflix Film Thriller rated TV-MA] ",
"The Ridiculous 6 [Netflix Film Comedy rated TV-14]",
"The Ritual [Movie Horror rated TV-MA]",
"The Siege of Jadotville [Netflix Film Drama rated TV-MA]",
"The Silence [Netflix Film Horror rated TV-14]",
"The Sinner [TV Series Thriller rated TV-MA]",
"The Sixth Sense [Movie Thriller rated PG-13]",
"The Society [Netflix Series Drama rated TV-MA]",
"The Spiderwick Chronicles [Movie Kids & Family rated PG]",
"The Staircase [Netflix Series Documentary rated TV-MA]",
"The Star [Animated Movie Kids & Family rated PG]",
"The Theory of Everything [Movie Drama rated PG-13]",
"The Three Musketeers [Disney Animated Movie Kids & Family rated G]",
"The Titan [Netflix Film Sci-Fi & Fantasy rated TV-MA]",
"The Toys That Made Us [Netflix Series Documentary rated TV-14]",
"The Trader (Sovdagari) [Netflix Film Documentary rated TV-PG]",
"The Ugly Truth [Movie Comedy rated R]",
"The Umbrella Academy [Netflix Series Action rated TV-14]",
"The Vietnam War: A Film by Ken Burns and Lynn Novick [TV Series Thriller rated TV-MA]",
"The Waterboy [Movie Comedy rated PG-13]",
"The Week Of [Netflix Film Comedy rated TV-14]",
"The White Helmets [Netflix Film Documentary rated TV-14] (OSCAR WINNER: Best Short-Subject Documentary Film)",
"The Who Was? Show [Netflix Series Kids & Family rated TV-Y7]",
"The World's Most Extraordinary Homes [Netflix Series Documentary rated TV-G] (Description starts with season 2)",
"The Worst Witch [Netflix Series Kids & Family rated TV-Y7]",
"Theo Who Lived [Movie Documentary rated TV-14]",
"They'll Love Me When I'm Dead [Netflix Film Documentary rated TV-MA]",
"Thor: Ragnarok [Movie Action rated PG-13]",
"Three Generations [Movie Drama rated PG-13]",
"Tidelands [Netflix Series Drama rated TV-MA]",
"Tidying Up with Marie Kondo [Netflix Reality TV Series Reality TV rated TV-PG]",
"Tig [Netflix Film Documentary rated TV-14]",
"Tinker Bell and the Legend of the NeverBeast [Disney Animated Movie Kids & Family rated G]",
"To All the Boys I've Loved Before [Netflix Film Romance rated TV-14]",
"To Rome With Love [Movie Romance rated R]",
"To the Bone [Netflix Series Drama rated TV-MA]",
"Tokyo Trial [TV Series Drama rated TV-14]",
"Tony Robbins: I Am Not Your Guru [Netflix Series Documentary rated TV-MA]",
"Trailer Park Boys [Netflix Series Comedy rated TV-MA]",
"Trailer Park Boys: Out of the Park: USA [Netflix Series Comedy rated TV-MA]",
"Trailer Park Boys: The Animated Series [Netflix Animated Adult Series Comedy rated TV-MA]",
"Trailer Park Boys: Xmas Special [Movie Comedy rated TV-MA]",
"Traitors [Netflix Series Thriller rated TV-MA]",
"Tramps [Netflix Film Romance rated TV-MA]",
"Trash [Movie Drama rated R]",
"Travelers [Netflix Series Sci-Fi & Fantasy rated TV-MA]",
"Treasures from the Wreck of the Unbelievable [Documentary Drama rated TV-G]",
"Treehouse Detectives [Netflix Animated Series Kids & Family rated TV-Y]",
"Trigger Warning with Killer Mike [Netflix Series Documentary rated TV-MA]",
"Trinkets [Netflix Series Drama rated TV-MA]",
"Triple Frontier [Movie Action rated R]",
"Trollhunters: Tales of Arcadia [Netflix Animated Series Kids & Family rated TV-Y7-FV]",
"Trolls Holiday Special [Animated Movie Kids & Family rated TV-G]",
"Trolls: The Beat Goes On! [Netflix Animated Series Kids & Family rated TV-G]",
"Troy: Fall of a City [Netflix Series Action rated TV-MA]",
"True and the Rainbow Kingdom [Netflix Animated Series Kids & Family rated TV-Y]",
"True Memoirs of an International Assassin [Netflix Film Comedy rated TV-14]",
"True Tunes [Netflix Animated Series Kids & Family rated TV-Y]",
"True: Happy Hearts Day [Netflix Animated Film Kids & Family rated TV-Y]",
"True: Magical Friends [Netflix Series Kids & Family rated TV-Y]",
"True: Wonderful Wishes [Netflix Series Kids & Family rated TV-Y]",
"Tuca & Bertie [Netflix Animated Adult Series Comedy rated TV-MA]",
"Turn Up Charlie [Netflix Series Comedy rated TV-MA]",
"Twelve Forever [Netflix Animated Series Kids & Family rated TV-Y7] ",
"Ugly Delicious [Netflix Series Documentary rated TV-MA]",
"Unbreakable Kimmy Schmidt [Netflix Series Comedy rated TV-14]",
"Undercover Grandpa [Movie Action rated PG-13]",
"Unicorn Store [Netflix Film Comedy rated PG]",
"Unsolved [TV Series Drama rated TV-MA]",
"VeggieTales in the City [Netflix Animated Series Kids & Family rated TV-Y]",
"VeggieTales in the House [Netflix Animated Series Kids & Family rated TV-Y]",
"Velvet Buzzsaw [Netflix Film Drama rated R]",
"Virunga [Netflix Film Documentary rated TV-14]",
"Voltron: Legendary Defender [Netflix Animated Series Kids & Family rated TV-Y7-FV]",
"Voyeur [Netflix Film Documentary rated TV-MA]",
"W/ Bob & David [Netflix Series Comedy rated TV-MA]",
"W1A [British TV Series Comedy rated TV-MA]",
"Walk. Ride. Rodeo. [Netflix Film Drama rated PG]",
"Wanderlust [Netflix Series Drama rated TV-MA]",
"Wanted [Movie Thriller rated R]",
"Wanted [Netflix Series Drama rated TV-14]",
"War Horse [Movie Drama rated PG-13]",
"War Machine [Netflix Film Drama rated TV-MA]",
"Watership Down [Netflix Animated Series Drama rated TV-PG]",
"We're Lalaloopsy [Netflix Animated Series Kids & Family rated TV-Y]",
"Westside [Netflix Series Reality TV rated TV-MA]",
"Wet Hot American Summer [Movie Comedy rated R]",
"Wet Hot American Summer: First Day of Camp [Netflix Series Comedy rated TV-MA]",
"Wet Hot American Summer: Ten Years Later [Netflix Series Comedy rated TV-MA]",
"WHAT / IF [Netflix Series Thriller rated TV-MA]",
"What Happened to Monday [Netflix Film Sci-Fi & Fantasy rated TV-MA]",
"What Happened, Miss Simone? [Netflix Film Documentary rated TV-14]",
"Wheelman [Netflix Film Action rated TV-MA]",
"When They See Us [Netflix Series Drama rated TV-MA]",
"When We First Met [Netflix Series Comedy rated TV-PG]",
"Where's the Money [Movie Comedy rated R]",
"White Fang [Netflix Film Kids & Family rated TV-PG]",
"White Gold [Netflix Series Comedy rated TV-MA]",
"White Rabbit Project [Netflix Series Reality TV rated TV-PG]",
"Who the F**k Is That Guy? [Movie Documentary rated TV-MA]",
"Wild Wild Country [Netflix Series Documentary rated TV-MA]",
"Win It All [Netflix Film Comedy rated TV-MA]",
"Wine Country [Netflix Film Comedy rated R]",
"Winter on Fire: Ukraine's Fight for Freedom [Netflix Film Documentary Not Rated] (Both English and Ukrainian description)",
"Word Party [Netflix Animated Series Kids & Family rated TV-Y]",
"Workin' Moms [Netflix Series Comedy rated TV-MA]",
"World of Winx [Netflix Animated Series Kids & Family rated TV-Y7]",
"Wormwood [Netflix Series Documentary rated TV-14]",
"XOXO [Netflix Film Drama rated TV-MA]",
"YooHoo to the Rescue [Netflix Animated Series Romance rated TV-Y]",
"You Can't Fight Christmas [Movie Romance rated TV-PG]",
"You Get Me [Netflix Film Thriller rated TV-MA]",
"You vs. Wild [Netflix Interactive** Science & Nature Series Kids & Family rated TV-PG]",
"You [TV Series Thriller rated TV-MA]",
"Yummy Mummies [Netflix Series Reality TV rated TV-14]",
"Zion [Netflix Film Documentary rated TV-PG]",
"Zodiac [Movie Drama rated R] (Pull date Aug 6)",
"Zumbo's Just Desserts [Netflix Reality TV Series Reality TV rated TV-14]"]

if __name__ == '__main__':
    main()
